services:
  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: nour
      POSTGRES_PASSWORD: nour
      PGDATA: /var/lib/postgresql/ecommerce
    volumes:
        - postgres:/var/lib/postgresql/ecommerce
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
        - pgadmin:/var/lib/pgadmin
    ports:
        - "5050:80"
    networks:
        - microservices-net
    restart: unless-stopped


  mongodb:
    container_name: ms_mongo_db
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: nour
        MONGO_INITDB_ROOT_PASSWORD: nour
    networks:
      - microservices-net


  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: nour
      ME_CONFIG_MONGODB_ADMINPASSWORD: nour
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - microservices-net
    restart: always

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: