spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service



  data:
    mongodb:
      username: nour
      password: nour
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090